import Campaigns from '@/app/assets/Campaigns.svg';
import Card1 from '@/app/assets/Card1.png';
import Card2 from '@/app/assets/Card2.png';
import Card3 from '@/app/assets/Card3.png';
import Card4 from '@/app/assets/Card4.png';
import Card5 from '@/app/assets/Card5.png';
import Clock from '@/app/assets/Clock.svg';
import Community from '@/app/assets/Community.svg';
import Create from '@/app/assets/Create.svg';
import Debunks from '@/app/assets/Debunks.svg';
import Evidence from '@/app/assets/Evidence.svg';
import Facebook from '@/app/assets/Facebook.svg';
import FactCheckers from '@/app/assets/FactCheckers.svg';
import False from '@/app/assets/False.svg';
import Import from '@/app/assets/Import.svg';
import Instagram from '@/app/assets/Instagram.svg';
import LogoIcon from '@/app/assets/logo-icon.svg';
import Logo from '@/app/assets/logo.svg';
import LogoIcon2 from '@/app/assets/LogoIcon.svg';
import Request from '@/app/assets/Request.svg';
import Sponsor from '@/app/assets/Sponsor.svg';
import Sponsorships from '@/app/assets/Sponsorships.svg';
import StartCampaign from '@/app/assets/Start Campaign.svg';
import TikTok from '@/app/assets/TikTok.svg';
import Tips from '@/app/assets/Tips.svg';
import True from '@/app/assets/True.svg';
import X from '@/app/assets/X.svg';
import Youtube from '@/app/assets/Youtube.png';

export { Campaigns, Card1, Card2, Card3, Card4, Card5, Clock, Community, Create, Debunks, Evidence, Facebook, FactCheckers, False, Import, Instagram, Logo, LogoIcon, LogoIcon2, Request, Sponsor, Sponsorships, StartCampaign, TikTok, Tips, True, X, Youtube };

